# Generated by Django 5.2.17 on 2026-08-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField()),
                ('tag', models.CharField(max_length=30)),
                ('tone', models.CharField(blank=True, choices=[('', 'Neutral'), ('amber', 'Amber'), ('red', 'Red'), ('green', 'Green')], max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-posted_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Internet', 'Internet'), ('Mobile', 'Mobile'), ('TV', 'TV'), ('Voice', 'Voice'), ('Bundle', 'Bundle'), ('Business', 'Business'), ('Add-on', 'Add-on'), ('Equipment', 'Equipment')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ending', 'Ending soon'), ('expired', 'Expired'), ('at-risk', 'At risk')], default='active', max_length=10)),
                ('badges', models.CharField(blank=True, help_text='Comma-separated, e.g. Best seller, High payout', max_length=120)),
                ('blurb', models.TextField()),
                ('points', models.TextField(help_text='One selling point per line')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_period', models.CharField(blank=True, help_text='e.g. /mo for 12 mos', max_length=40)),
                ('was_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('spiff', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('spiff_note', models.CharField(blank=True, max_length=160)),
                ('eligibility', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('Internet', 'Internet'), ('Mobile', 'Mobile'), ('TV', 'TV'), ('Voice', 'Voice'), ('Bundle', 'Bundle'), ('Business', 'Business'), ('Add-on', 'Add-on'), ('Equipment', 'Equipment')], max_length=20)),
                ('icon', models.CharField(default='📦', help_text='Emoji shown on the card', max_length=8)),
                ('description', models.TextField()),
                ('price_note', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🔗', max_length=8)),
                ('label', models.CharField(max_length=80)),
                ('meta', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(default='#', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(default='Sales Agent', max_length=80)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('market', models.CharField(blank=True, max_length=80)),
                ('team', models.CharField(blank=True, max_length=60)),
                ('manager', models.CharField(blank=True, max_length=80)),
                ('tier', models.CharField(blank=True, max_length=30)),
                ('agent_since', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('SPIFF', 'SPIFF'), ('Tiered bonus', 'Tiered bonus'), ('Multiplier', 'Multiplier'), ('Quality bonus', 'Quality bonus'), ('Recognition', 'Recognition')], default='SPIFF', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ending', 'Ending soon'), ('expired', 'Expired'), ('at-risk', 'At risk')], default='active', max_length=10)),
                ('payout', models.CharField(help_text='e.g. $75 per bundle sale', max_length=120)),
                ('period', models.CharField(help_text='e.g. Aug 1 - Sep 15, 2026', max_length=60)),
                ('description', models.TextField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='sales', max_length=30)),
                ('earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potential', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('offers', models.ManyToManyField(blank=True, related_name='incentives', to='portal.offer')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. August 2026', max_length=40)),
                ('days_left', models.PositiveSmallIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('unit_target', models.PositiveIntegerField(default=1)),
                ('gross_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spiff_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_payout_date', models.CharField(blank=True, max_length=40)),
                ('last_month_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('chargebacks', models.PositiveSmallIntegerField(default=0)),
                ('chargeback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('rank_of', models.PositiveSmallIntegerField(default=0)),
                ('ytd_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_current', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['-is_current', '-id'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='portal.product'),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='portal.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(default='#', max_length=300)),
                ('icon', models.CharField(default='🔗', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portal.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob', models.CharField(max_length=40, verbose_name='line of business')),
                ('sold', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['order', 'lob'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_on', models.DateField()),
                ('order_no', models.CharField(max_length=30, unique=True)),
                ('customer', models.CharField(max_length=120)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('spiff', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Installed', 'Installed'), ('Active', 'Active'), ('Pending install', 'Pending install'), ('Scheduled', 'Scheduled'), ('Chargeback', 'Chargeback')], default='Pending install', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='portal.agentprofile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='portal.offer')),
            ],
            options={
                'ordering': ['-sold_on', '-order_no'],
            },
        ),
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='portal.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='portal.specgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
