# Generated by Django 5.2.17 on 2026-08-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive days signed in'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime experience points'),
        ),
    ]
