# Generated by Django 5.2.17 on 2026-08-31 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_agentprofile_last_seen_agentprofile_streak_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='attach_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='avg_handle_time',
            field=models.CharField(blank=True, help_text='mm:ss', max_length=10),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='calls_converted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='calls_handled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='queue_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('blurb', models.CharField(help_text='What this role can do', max_length=200)),
                ('accent', models.CharField(default='blue', max_length=20)),
                ('is_available', models.BooleanField(default=False, help_text='Unchecked roles show on the picker but cannot be entered')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
