# Generated by Django 5.2.17 on 2026-08-31 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_performancesnapshot_attach_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('icon', models.CharField(default='🏅', max_length=8)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('is_earned', models.BooleanField(default=False)),
                ('is_milestone', models.BooleanField(default=False, help_text='Counts toward the second badge tally')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='e.g. Exception Flagged', max_length=40)),
                ('text', models.CharField(max_length=240)),
                ('ago', models.CharField(help_text='e.g. 2m ago', max_length=20)),
                ('tone', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. August 2026', max_length=20, unique=True)),
                ('starts_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Gig Internet PSU', max_length=60)),
                ('short_label', models.CharField(blank=True, help_text='e.g. GIG', max_length=12)),
                ('points', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('threshold_points', models.PositiveIntegerField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='points_balance',
            field=models.PositiveIntegerField(default=0, help_text='Spendable reward points'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='incentive',
            name='bucket',
            field=models.CharField(choices=[('active', 'Active'), ('launched', 'Just Launched'), ('ending', 'Ending Soon'), ('previous', 'Previous')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='incentive',
            name='days_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incentive',
            name='is_points_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentive',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incentive',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='incentive',
            name='short_code',
            field=models.CharField(blank=True, help_text='e.g. Inc 01', max_length=12),
        ),
        migrations.AddField(
            model_name='incentive',
            name='unit_rate_label',
            field=models.CharField(blank=True, help_text='e.g. $10/unit', max_length=40),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(help_text='e.g. TKT-00001', max_length=20, unique=True)),
                ('subject', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Commission Error', 'Commission Error'), ('Bonus / SPIF Not Applied', 'Bonus / SPIF Not Applied'), ('Clawback Dispute', 'Clawback Dispute'), ('Missing Payout', 'Missing Payout')], max_length=40)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Open', max_length=12)),
                ('detail', models.TextField(blank=True)),
                ('raised_on', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['-raised_on', 'ticket_no'],
            },
        ),
        migrations.CreateModel(
            name='MtdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. GIG, INT PSU, VID PSU', max_length=20)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('pct_of_points', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_focus', models.BooleanField(default=False, help_text='Best improvement opportunity')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtd', to='portal.agentprofile')),
            ],
            options={
                'verbose_name_plural': 'MTD categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(help_text='e.g. EMP-78432', max_length=20)),
                ('job_code', models.CharField(help_text='e.g. AE-INB', max_length=20)),
                ('location', models.CharField(help_text='e.g. Southwest Region', max_length=60)),
                ('incentive_id', models.CharField(help_text='e.g. RIBSR2606ACQ', max_length=30)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('rank_of', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('potential_payout', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('eligibility', models.CharField(default='Eligible', max_length=30)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('finalization_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='portal.agentprofile')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.tier')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('units_needed', models.PositiveIntegerField(default=0)),
                ('daily_target', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='portal.agentprofile')),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='portal.incentive')),
                ('target_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.tier')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TrendPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='e.g. Jan', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
