# Generated by Django 5.2.17 on 2026-08-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_badge_notification_period_pointsrule_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='role_type',
            field=models.CharField(choices=[('agent', 'Field Agent'), ('lead', 'Team Lead'), ('manager', 'Manager')], default='agent', help_text='Drives what this person can see', max_length=10),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_led', to='portal.agentprofile')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
