# Generated by Django 5.2.17 on 2026-08-31 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_agentprofile_role_type_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='portal.team'),
        ),
    ]
