# Generated by Django 5.2.17 on 2026-08-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_agentprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='previous_rank',
            field=models.PositiveIntegerField(default=0, help_text='Last period, for movement arrows'),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(default='🎯', max_length=8)),
                ('xp', models.PositiveSmallIntegerField(default=25)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
