# Generated by Django 5.2.17 on 2026-08-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_scorecard_previous_rank_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtdcategory',
            name='star_pct',
            field=models.DecimalField(decimal_places=1, default=0, help_text='What a Star-tier rep does in this category', max_digits=5),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='days_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='period_days',
            field=models.PositiveSmallIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='point_streak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive days scoring points'),
        ),
    ]
