# Generated by Django 5.2.17 on 2026-08-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_mtdcategory_star_pct_scorecard_days_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='next_label',
            field=models.CharField(blank=True, help_text='Plan-defined step to this tier, e.g. "Next 180" or "Top 33"', max_length=20),
        ),
    ]
