# Generated by Django 5.2.17 on 2026-08-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_tier_next_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='portal.agentprofile'),
        ),
        migrations.AddField(
            model_name='persona',
            name='role_type',
            field=models.CharField(choices=[('agent', 'Field Agent'), ('lead', 'Team Lead'), ('manager', 'Manager')], default='agent', help_text='Groups the picker on the sign-in screen', max_length=10),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('agent', 'name')},
        ),
    ]
