# Generated by Django 5.2.17 on 2026-08-31 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_badge_agent_persona_role_type_alter_badge_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('product', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Internet', 'Internet'), ('Mobile', 'Mobile'), ('TV', 'TV'), ('Voice', 'Voice'), ('Bundle', 'Bundle'), ('Business', 'Business'), ('Add-on', 'Add-on'), ('Equipment', 'Equipment')], max_length=20)),
                ('units', models.PositiveIntegerField(default=0)),
                ('change_pct', models.DecimalField(decimal_places=1, default=0, help_text='Movement against last period', max_digits=5)),
                ('attach_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('period', models.CharField(default='August 2026', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['region', 'order', '-units'],
            },
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-raised_on', '-id']},
        ),
        migrations.CreateModel(
            name='IncentivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rationale', models.TextField(help_text='Why this plan, and which trend it responds to')),
                ('product', models.CharField(help_text='What you want sold more of', max_length=80)),
                ('category', models.CharField(choices=[('Internet', 'Internet'), ('Mobile', 'Mobile'), ('TV', 'TV'), ('Voice', 'Voice'), ('Bundle', 'Bundle'), ('Business', 'Business'), ('Add-on', 'Add-on'), ('Equipment', 'Equipment')], max_length=20)),
                ('reward_type', models.CharField(choices=[('cash', 'Cash per unit'), ('points', 'Points per unit')], default='cash', max_length=10)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('target_units', models.PositiveIntegerField(default=0)),
                ('runs_from', models.DateField()),
                ('runs_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('decision_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_created', to='portal.agentprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_decided', to='portal.agentprofile')),
                ('team', models.ForeignKey(help_text='Who the incentive is for', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='portal.team')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
