# Generated by Django 5.2.17 on 2026-09-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_markettrend_alter_dispute_options_incentiveplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_decided', to='portal.agentprofile'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('Awaiting lead', 'Awaiting team lead'), ('In Review', 'Approved - with payouts'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected by lead')], default='Awaiting lead', max_length=14),
        ),
    ]
