# Generated by Django 5.2.17 on 2026-09-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_dispute_decided_by_dispute_decision_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(default='📊', max_length=8)),
                ('agents', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attainment', models.PositiveSmallIntegerField(default=0)),
                ('avg_payout', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('change_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-spend'],
            },
        ),
        migrations.CreateModel(
            name='PayoutException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('High payout', 'Payout well above channel average'), ('Low volume', 'Volume well below channel norm'), ('Duplicate', 'Possible duplicate credit'), ('Near cap', 'Approaching the payout cap')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detail', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending review'), ('Escalated', 'Escalated'), ('Cleared', 'Cleared for payment')], default='Pending', max_length=10)),
                ('flagged_on', models.DateField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='portal.agentprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_decided', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['status', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('period', models.CharField(default='August 2026', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_set', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['region'],
                'unique_together': {('region', 'period')},
            },
        ),
    ]
