# Generated by Django 5.2.17 on 2026-09-01 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_channel_payoutexception_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='approval',
            field=models.CharField(choices=[('Awaiting lead', 'Awaiting team lead'), ('Approved', 'Incentive approved'), ('Rejected', 'Rejected by lead')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_decided', to='portal.agentprofile'),
        ),
        migrations.AddField(
            model_name='sale',
            name='decided_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='decision_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
