# Generated by Django 5.2.17 on 2026-09-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_sale_approval_sale_decided_by_sale_decided_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Open', 'Open - not yet calculated'), ('Calculated', 'Calculated - awaiting approval'), ('Approved', 'Approved for payroll')], default='Open', max_length=12)),
                ('agent_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plan_commitments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('calculated_on', models.DateTimeField(blank=True, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closes_approved', to='portal.agentprofile')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closes_calculated', to='portal.agentprofile')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('region', 'period')},
            },
        ),
    ]
