# Generated by Django 5.2.17 on 2026-09-03 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_periodclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiveplan',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='portal.incentiveplan'),
        ),
        migrations.AddField(
            model_name='incentiveplan',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
