# Generated by Django 5.2.17 on 2026-09-03 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_incentiveplan_cloned_from_incentiveplan_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60, unique=True)),
                ('coaching_threshold', models.PositiveSmallIntegerField(default=70, help_text='Attainment below this flags an agent for coaching')),
                ('exception_threshold', models.DecimalField(decimal_places=2, default=3000, help_text='A payout above this is held for review', max_digits=9)),
                ('close_reminder_days', models.PositiveSmallIntegerField(default=3, help_text='Days before period end to raise the close reminder')),
                ('notify_on_dispute', models.BooleanField(default=True)),
                ('notify_on_plan', models.BooleanField(default=True)),
                ('notify_on_close', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to='portal.agentprofile')),
            ],
        ),
    ]
