# Generated by Django 5.2.17 on 2026-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='presents_as',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('unspecified', 'Prefer not to say')], default='unspecified', help_text="Chooses the assistant character's appearance for this person", max_length=12),
        ),
    ]
