# Generated by Django 5.2.17 on 2026-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_agentprofile_presents_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='last_roll_face',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='last_roll_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
